export const FETCH_POST_COMMENT_TREES_REQUEST =
    "FETCH_POST_COMMENT_TREES_REQUEST";
export const FETCH_POST_COMMENT_TREES_SUCCESS =
    "FETCH_POST_COMMENT_TREES_SUCCESS";
export const FETCH_POST_COMMENT_TREES_FAILURE =
    "FETCH_POST_COMMENT_TREES_FAILURE";
export const CREATE_COMMENT_REQUEST = "CREATE_COMMENT_REQUEST";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAILURE = "CREATE_COMMENT_FAILURE";
export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAILURE = "DELETE_COMMENT_FAILURE";
export const UPDATE_COMMENT_REQUEST = "UPDATE_COMMENT_REQUEST";
export const UPDATE_COMMENT_SUCCESS = "UPDATE_COMMENT_SUCCESS";
export const UPDATE_COMMENT_FAILURE = "UPDATE_COMMENT_FAILURE";
export const COMMENT_VOTE_SUCCESS = "COMMENT_VOTE_SUCCESS";

export const TOGGLE_INITIAL_VISIT_FLAG = "TOGGLE_INITIAL_VISIT_FLAG";

export const UPDATE_SORT_BY_OPTION = "UPDATE_SORT_BY_OPTION";

export const FETCH_USER_PROFILE_REQUEST = "FETCH_USER_PROFILE_REQUEST";
export const FETCH_USER_PROFILE_SUCCESS = "FETCH_USER_PROFILE_SUCCESS";
export const FETCH_USER_PROFILE_FAILURE = "FETCH_USER_PROFILE_FAILURE";
export const SET_USER_PROFILE_VIEW = "SET_USER_PROFILE_VIEW";

export const VOTE_REQUEST = "VOTE_REQUEST";
export const VOTE_SUCCESS = "VOTE_SUCCESS";
export const VOTE_FAILURE = "VOTE_FAILURE";

export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILURE = "SEARCH_FAILURE";
export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const SET_SEARCH_RESULTS_VIEW = "SET_SEARCH_RESULTS_VIEW";
export const RESETOPASU_REQUEST = "RESETOPASU_REQUEST";
export const RESETOPASU_SUCCESS = "RESETOPASU_SUCCESS";
export const RESETOPASU_FAILURE = "RESETOPASU_FAILURE";
export const FETCH_SUB_DETAIL_REQUEST = "FETCH_SUB_DETAIL_REQUEST";
export const FETCH_SUB_DETAIL_SUCCESS = "FETCH_SUB_DETAIL_SUCCESS";
export const FETCH_SUB_DETAIL_FAILURE = "FETCH_SUB_DETAIL_FAILURE";
export const SET_SUB_TO_HOME = "SET_SUB_TO_HOME";
export const SUBREDDIT_SUBSCRIBE_REQUEST = "SUBREDDIT_SUBSCRIBE_REQUEST";
export const SUBREDDIT_SUBSCRIBE_SUCCESS = "SUBREDDIT_SUBSCRIBE_SUCCESS";
export const SUBREDDIT_SUBSCRIBE_FAILURE = "SUBREDDIT_SUBSCRIBE_FAILURE";
export const CREATE_SUBREDDIT_REQUEST = "CREATE_SUBREDDIT_REQUEST";
export const CREATE_SUBREDDIT_SUCCESS = "CREATE_SUBREDDIT_SUCCESS";
export const CREATE_SUBREDDIT_FAILURE = "CREATE_SUBREDDIT_FAILURE";
export const RESETOKAKUNIN_REQUEST = "RESETOKAKUNIN_REQUEST";
export const RESETOKAKUNIN_SUCCESS = "RESETOKAKUNIN_SUCCESS";
export const RESETOKAKUNIN_FAILURE = "RESETOKAKUNIN_FAILURE";
export const DUMMY_LUSI_REQUEST = "DUMMY_LUSI_REQUEST";
export const DUMMY_LUSI_SUCCESS = "DUMMY_LUSI_SUCCESS";
export const DUMMY_LUSI_FAILURE = "DUMMY_LUSI_FAILURE";

export const FETCH_POST_LIST_REQUEST = "FETCH_POST_LIST_REQUEST";
export const FETCH_POST_LIST_SUCCESS = "FETCH_POST_LIST_SUCCESS";
export const FETCH_POST_LIST_FAILURE = "FETCH_POST_LIST_FAILURE";
export const FETCH_POST_LIST_NEXT_REQUEST = "FETCH_POST_LIST_NEXT_REQUEST";
export const FETCH_POST_LIST_NEXT_SUCCESS = "FETCH_POST_LIST_NEXT_SUCCESS";
export const FETCH_POST_LIST_NEXT_FAILURE = "FETCH_POST_LIST_NEXT_FAILURE";
export const FETCH_PXULW_LIST_REQUEST = "FETCH_PXULW_LIST_REQUEST";
export const FETCH_PXULW_LIST_SUCCESS = "FETCH_PXULW_LIST_SUCCESS";
export const FETCH_PXULW_LIST_FAILURE = "FETCH_PXULW_LIST_FAILURE";
export const FETCH_PXULW_LIST_NEXT_REQUEST = "FETCH_PXULW_LIST_NEXT_REQUEST";
export const FETCH_PXULW_LIST_NEXT_SUCCESS = "FETCH_PXULW_LIST_NEXT_SUCCESS";
export const FETCH_PXULW_LIST_NEXT_FAILURE = "FETCH_PXULW_LIST_NEXT_FAILURE";
export const FETCH_POST_DETAIL_REQUEST = "FETCH_POST_DETAIL_REQUEST";
export const FETCH_POST_DETAIL_SUCCESS = "FETCH_POST_DETAIL_SUCCESS";
export const FETCH_POST_DETAIL_FAILURE = "FETCH_POST_DETAIL_FAILURE";
export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAILURE = "CREATE_POST_FAILURE";
export const CLEAR_CREATE_POST_ERROR = "CLEAR_CREATE_POST_ERROR";
export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE";
export const DELETE_PXULW_REQUEST = "DELETE_PXULW_REQUEST";
export const DELETE_PXULW_SUCCESS = "DELETE_PXULW_SUCCESS";
export const DELETE_PXULW_FAILURE = "DELETE_PXULW_FAILURE";
export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_FAILURE = "UPDATE_POST_FAILURE";
export const POST_VOTE_SUCCESS = "POST_VOTE_SUCCESS";
export const PXULW_VOTE_SUCCESS = "PXULW_VOTE_SUCCESS";
export const TOGGLE_POST_EDITOR = "TOGGLE_POST_EDITOR";

export const USER_AUTH_LOGIN_REQUEST = "USER_AUTH_LOGIN_REQUEST";
export const USER_AUTH_RESEND_ACTIVATION_EMAIL_REQUEST = "USER_AUTH_RESEND_ACTIVATION_EMAIL_REQUEST";
export const USER_AUTH_UPDATE_REQUEST = "USER_AUTH_UPDATE_REQUEST";
export const USER_AUTH_UPDATE_SUCCESS = "USER_AUTH_UPDATE_SUCCESS";
export const USER_AUTH_UPDATE_FAILURE = "USER_AUTH_UPDATE_FAILURE";
export const USER_AUTH_LOGOUT_REQUEST = "USER_AUTH_LOGOUT_REQUEST";
export const USER_AUTH_LOGOUT_SUCCESS = "USER_AUTH_LOGOUT_SUCCESS";
export const USER_AUTH_LOGOUT_FAILURE = "USER_AUTH_LOGOUT_FAILURE";
export const USER_AUTH_SUBSCRIBE_SUBREDDIT = "USER_AUTH_SUBSCRIBE_SUBREDDIT";
export const USER_AUTH_UNSUBSCRIBE_SUBREDDIT =
    "USER_AUTH_UNSUBSCRIBE_SUBREDDIT";

export const HIDE_USER_AUTH_MODAL = "HIDE_USER_AUTH_MODAL";
export const UPDATE_USER_AUTH_MODAL_ERROR = "UPDATE_USER_AUTH_MODAL_ERROR";

export const API_SUB_DETAIL = "API_SUB_DETAIL";
export const API_SUB_POST_LIST = "API_SUB_POST_LIST";

export const API_USER_PXULW_LIST = "API_USER_PXULW_LIST";
export const API_USER_PXULW_LIST_NEXT = "API_USER_PXULW_LIST_NEXT";

export const API_SUB_POST_LIST_NEXT = "API_SUB_POST_LIST_NEXT";
export const API_SUBREDDIT_SUBSCRIBE = "API_SUBREDDIT_SUBSCRIBE";
export const API_CREATE_SUBREDDIT = "API_CREATE_SUBREDDIT";
export const API_DUMMY_LUSI = "API_DUMMY_LUSI";
export const API_SIGNUP = "API_SIGNUP";

export const API_USER_AUTH_UPDATE = "API_USER_AUTH_UPDATE";
export const API_USER_AUTH_LOGOUT = "API_USER_AUTH_LOGOUT";
export const API_USER_AUTH_LOGIN = "API_USER_AUTH_LOGIN";
export const API_USER_AUTH_RESEND_ACTIVATION_EMAIL = "API_USER_AUTH_RESEND_ACTIVATION_EMAIL";
export const API_USER_AUTH_REGISTER = "API_USER_AUTH_REGISTER";
export const API_CREATE_POST = "API_CREATE_POST";
export const API_DELETE_POST = "API_DELETE_POST";
export const API_UPDATE_POST = "API_UPDATE_POST";
export const API_POST_DETAIL = "API_POST_DETAIL";
export const API_POST_COMMENT_TREES = "API_POST_COMMENT_TREES";
export const API_CREATE_COMMENT = "API_CREATE_COMMENT";
export const API_DELETE_COMMENT = "API_DELETE_COMMENT";
export const API_UPDATE_COMMENT = "API_UPDATE_COMMENT";
export const API_VOTE = "API_VOTE";
export const API_SEARCH = "API_SEARCH";
export const API_USER_PROFILE = "API_USER_PROFILE";
