export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const RESEND_ACTIVATION_EMAIL_URL_SUCCESS = "RESEND_ACTIVATION_EMAIL_URL_SUCCESS";
export const RESEND_ACTIVATION_EMAIL_URL_FAIL = "RESEND_ACTIVATION_EMAIL_URL_FAIL";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const USER_LOADED_SUCCESS = "USER_LOADED_SUCCESS";
export const USER_LOADED_FAIL = "USER_LOADED_FAIL";

export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const ACTIVATODOES_SUCCESS = "ACTIVATODOES_SUCCESS";
export const ACTIVATODOES_FAIL = "ACTIVATODOES_FAIL";
export const RESETOKAKUNIN_SUCCESS = "RESETOKAKUNIN_SUCCESS";
export const RESETOKAKUNIN_FAIL = "RESETOKAKUNIN_FAIL";

export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL";
export const LOGOUT = "LOGOUT";

export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_FAIL = "PASSWORD_RESET_FAIL";
export const PASSWORD_RESET_CONFIRM_SUCCESS = "PASSWORD_RESET_CONFIRM_SUCCESS";
export const PASSWORD_RESET_CONFIRM_FAIL = "PASSWORD_RESET_CONFIRM_FAIL";